export const MODEL_RECENCY_MONTH_WINDOW = 18;
export const MODEL_RECENCY_SCORE_FLOOR = 0.2;

export const CHATBOT_SHARE_CONVERGENCE = 0.42;
export const API_SHARE_CONVERGENCE = 0.18;

export const CHATBOT_MODEL_ACQUISITION_DECAY = 0.9;
export const API_MODEL_ACQUISITION_DECAY = 0.97;

export const CHATBOT_MODEL_AGE_CHURN_COEFFICIENT = 0.0045;
export const API_MODEL_AGE_CHURN_COEFFICIENT = 0.0022;
export const MODEL_CHURN_FLOOR = 0.005;
export const MODEL_CHURN_CEILING = 0.5;

export const CONSUMER_RECENCY_BASELINE = 0.2;
export const CONSUMER_RECENCY_MULTIPLIER_COEFFICIENT = 1.4;
export const CONSUMER_SPEED_BONUS_COEFFICIENT = 0.003;
export const CONSUMER_MULTIMODAL_BONUS_COEFFICIENT = 0.003;
export const CHATBOT_DEEP_CONVERSATION_MULTIPLIER = 3.5;
export const CHATBOT_STANDARD_CONVERSATION_MULTIPLIER = 1.5;
export const BUDGET_CLIFF_DECAY = 4.8;
export const BUDGET_CLIFF_FLOOR = 0.05;
export const INADEQUATE_PLAN_APPEAL_MULTIPLIER = 0.5;
export const PLAN_PRICE_TIEBREAKER_COEFFICIENT = 0.02;

export const CHATBOT_TOKENS_PER_POD_MILLIONS = 750;
export const BASE_CONTEXT_WINDOW = 8;
export const CONTEXT_OVERHEAD_STEP_WINDOW = 32;
export const CONTEXT_OVERHEAD_STEP_RATE = 0.25;
export const SERVING_VARIABLE_COST_PER_POD = 2500;
export const BURST_CLOUD_COST_PER_POD = 16000;
export const BURST_CLOUD_CAPACITY_RATIO = 0.65;
export const BURST_CLOUD_MIN_PODS = 12;
export const DATACENTER_PROVISIONING_MONTHS = 3;
export const DATACENTER_PROVISIONING_WEEKS = DATACENTER_PROVISIONING_MONTHS * 4;
export const SERVING_HARDWARE_BASE_EFFICIENCY = 1;
export const SERVING_HARDWARE_UPGRADE_EFFICIENCY = 0.08;

export const TRAINING_PARAMETER_STEP_MONTHS = 10;
export const TRAINING_MEMORY_STEP_MONTHS = 6;
export const TRAINING_CONTEXT_STEP_MONTHS = 4;
export const TRAINING_DATA_UNIT_MONTHS = 2.8;
export const TRAINING_GOAL_COMPLEXITY_MONTHS = 2.8;
export const TRAINING_ACTIVE_GOAL_MONTHS = 0.8;
export const TRAINING_DERIVED_MODEL_MONTHS = 8;

export const TRAINING_WEB_DATA_FAILURE_RISK = 0.06;
export const TRAINING_LICENSED_DATA_FAILURE_RISK = 0;
export const TRAINING_SYNTH_DATA_FAILURE_RISK = -0.02;
export const TRAINING_PARAMETER_STEP_FAILURE_RISK = 0.03;
export const TRAINING_MEMORY_STEP_FAILURE_RISK = 0.018;
export const TRAINING_CONTEXT_STEP_FAILURE_RISK = 0.012;
export const TRAINING_GOAL_COMPLEXITY_FAILURE_RISK = 0.01;
export const TRAINING_DATA_UNIT_FAILURE_RISK = 0.004;

export const TRAINING_PARAMETER_EXPANSION_CAPABILITY = 0.38;
export const TRAINING_MEMORY_EXPANSION_CAPABILITY = 0.32;
export const TRAINING_CONTEXT_EXPANSION_CAPABILITY = 0.12;
export const TRAINING_DATA_CAPABILITY = 0.9;

export const TRAINING_PARAMETER_STEP_INFERENCE = 0.18;
export const TRAINING_MEMORY_STEP_INFERENCE = 0.1;
export const TRAINING_CONTEXT_STEP_INFERENCE = 0.04;

export const TRAINING_CONTEXT_STEP_TRUST = 0.25;
export const TRAINING_SPEED_TRUST_PENALTY = 2.4;
export const TRAINING_ACCURACY_TRUST_BONUS = 8;
export const TRAINING_REASONING_TRUST_BONUS = 4;

export const PARAMETER_STEP_BASE_COST = 650000;
export const MEMORY_STEP_BASE_COST = 325000;
export const CONTEXT_STEP_BASE_COST = 180000;

export const RESEARCHER_DISCOUNT_MIN = 0.001;
export const RESEARCHER_DISCOUNT_MAX = 0.0045;

export const COMPETITOR_RELEASE_SHOCK_COEFFICIENT = 0.002;

// Switching friction
export const FRICTION_MAX_TENURE_WEEKS = 52;
export const FRICTION_MAX_MULTIPLIER = 1.55;
export const FRICTION_DEVELOPER_SCALE = 1.4;
export const FRICTION_CASUAL_SCALE = 0.6;
export const FRICTION_BUSINESS_SCALE = 1.8;
export const COMPETITOR_PRICE_REVIEW_INTERVAL_WEEKS = 8;
export const COMPETITOR_PRICE_RESPONSE_THRESHOLD = 0.2;
export const COMPETITOR_PRICE_CUT_AGGRESSION = 0.85;
export const COMPETITOR_PRICE_CUT_BALANCED = 0.92;
export const COMPETITOR_PRICE_CUT_DISCIPLINED = 0.96;
export const COMPETITOR_LOSS_LEADER_MIN_SHARE = 0.0;
export const COMPETITOR_PRICE_FLOOR_MULTIPLIER = 0.55;
export const COMPETITOR_PRICE_RESTORE_RATE = 0.04;

// Post-training
export const POST_TRAINING_RLHF_TRUST_BONUS = 8;
export const POST_TRAINING_RLHF_WEEKS_BASE = 3;
export const POST_TRAINING_DOMAIN_GOAL_BOOST = 12;
export const POST_TRAINING_DOMAIN_WEEKS_BASE = 2;
export const POST_TRAINING_RED_TEAM_WEEKS_BASE = 2;
export const POST_TRAINING_RED_TEAM_SAFETY_REDUCTION = 0.65;
export const POST_TRAINING_SKIP_TRUST_PENALTY = -12;
export const POST_TRAINING_SKIP_INCIDENT_RISK_PER_WEEK = 0.004;
export const POST_TRAINING_MEDICAL_GOV_TRUST_GATE = 65;

// Price sensitivity drift
export const MATURITY_SENSITIVITY_DRIFT_MAX = 0.6;
export const MATURITY_FULL_WEEKS = 208;
export const MACRO_SHOCK_SENSITIVITY_BOOST = 0.35;
export const MACRO_SHOCK_WEEKS_MIN = 8;
export const MACRO_SHOCK_WEEKS_MAX = 24;
export const MACRO_SHOCK_INTERVAL_MIN_WEEKS = 52;
export const BUDGET_NORMALIZATION_RATE = 0.008;
export const BUDGET_NORMALIZATION_FLOOR = 0.5;

// Model lifecycle
export const MODEL_MAINTENANCE_BASE_COST = 8000;
export const MODEL_MAINTENANCE_FRONTIER_MULTIPLIER = 3.5;
export const MODEL_MAINTENANCE_LARGE_MULTIPLIER = 1.8;
export const MODEL_MAINTENANCE_MEDIUM_MULTIPLIER = 1.0;
export const MODEL_MAINTENANCE_SMALL_MULTIPLIER = 0.5;
export const DEPRECATION_CHURN_BOOST_PER_WEEK = 0.04;
export const DEPRECATION_MIGRATION_WEEKS = 12;
export const SAFETY_INCIDENT_TRUST_PENALTY = 14;
export const SAFETY_INCIDENT_THRESHOLD = 0.25;
