export const MODEL_RECENCY_MONTH_WINDOW = 18;
export const MODEL_RECENCY_SCORE_FLOOR = 0.2;

export const CHATBOT_SHARE_CONVERGENCE = 0.42;
export const API_SHARE_CONVERGENCE = 0.18;

export const CHATBOT_MODEL_ACQUISITION_DECAY = 0.9;
export const API_MODEL_ACQUISITION_DECAY = 0.97;

export const CHATBOT_MODEL_AGE_CHURN_COEFFICIENT = 0.0045;
export const API_MODEL_AGE_CHURN_COEFFICIENT = 0.0022;
export const MODEL_CHURN_FLOOR = 0.005;
export const MODEL_CHURN_CEILING = 0.5;

export const CONSUMER_RECENCY_BASELINE = 0.2;
export const CONSUMER_RECENCY_MULTIPLIER_COEFFICIENT = 1.4;
export const CONSUMER_SPEED_BONUS_COEFFICIENT = 0.003;
export const CONSUMER_MULTIMODAL_BONUS_COEFFICIENT = 0.003;
export const CHATBOT_DEEP_CONVERSATION_MULTIPLIER = 3.5;
export const CHATBOT_STANDARD_CONVERSATION_MULTIPLIER = 1.5;
export const BUDGET_CLIFF_DECAY = 4.8;
export const BUDGET_CLIFF_FLOOR = 0.05;
export const INADEQUATE_PLAN_APPEAL_MULTIPLIER = 0.5;
export const PLAN_PRICE_TIEBREAKER_COEFFICIENT = 0.02;

export const CHATBOT_TOKENS_PER_POD_MILLIONS = 50;
export const BASE_CONTEXT_WINDOW = 8;
export const CONTEXT_OVERHEAD_STEP_WINDOW = 32;
export const CONTEXT_OVERHEAD_STEP_RATE = 0.25;

export const TRAINING_PARAMETER_STEP_MONTHS = 10;
export const TRAINING_MEMORY_STEP_MONTHS = 6;
export const TRAINING_CONTEXT_STEP_MONTHS = 4;
export const TRAINING_DATA_UNIT_MONTHS = 2.8;
export const TRAINING_GOAL_COMPLEXITY_MONTHS = 2.8;
export const TRAINING_ACTIVE_GOAL_MONTHS = 0.8;
export const TRAINING_DERIVED_MODEL_MONTHS = 8;

export const TRAINING_WEB_DATA_FAILURE_RISK = 0.06;
export const TRAINING_LICENSED_DATA_FAILURE_RISK = 0;
export const TRAINING_SYNTH_DATA_FAILURE_RISK = -0.02;
export const TRAINING_PARAMETER_STEP_FAILURE_RISK = 0.03;
export const TRAINING_MEMORY_STEP_FAILURE_RISK = 0.018;
export const TRAINING_CONTEXT_STEP_FAILURE_RISK = 0.012;
export const TRAINING_GOAL_COMPLEXITY_FAILURE_RISK = 0.01;
export const TRAINING_DATA_UNIT_FAILURE_RISK = 0.004;

export const TRAINING_PARAMETER_EXPANSION_CAPABILITY = 0.38;
export const TRAINING_MEMORY_EXPANSION_CAPABILITY = 0.32;
export const TRAINING_CONTEXT_EXPANSION_CAPABILITY = 0.12;
export const TRAINING_DATA_CAPABILITY = 0.9;

export const TRAINING_PARAMETER_STEP_INFERENCE = 0.18;
export const TRAINING_MEMORY_STEP_INFERENCE = 0.1;
export const TRAINING_CONTEXT_STEP_INFERENCE = 0.04;

export const TRAINING_CONTEXT_STEP_TRUST = 0.25;
export const TRAINING_SPEED_TRUST_PENALTY = 2.4;
export const TRAINING_ACCURACY_TRUST_BONUS = 8;
export const TRAINING_REASONING_TRUST_BONUS = 4;

export const PARAMETER_STEP_BASE_COST = 650000;
export const MEMORY_STEP_BASE_COST = 325000;
export const CONTEXT_STEP_BASE_COST = 180000;

export const RESEARCHER_DISCOUNT_MIN = 0.001;
export const RESEARCHER_DISCOUNT_MAX = 0.0045;

export const COMPETITOR_RELEASE_SHOCK_COEFFICIENT = 0.002;
